// actionTypes.ts
export const RESET_ACTION = "RESET_ACTION";
export const RESET_ACTION_LOGGING = "RESET_ACTION_LOGGING";
export const ADD_ACTION_REQUEST = "ADD_ACTION_REQUEST";
export const ADD_ACTION_SUCCESS = "ADD_ACTION_SUCCESS";
export const ADD_ACTION_FAIL = "ADD_ACTION_FAIL";
export const GET_ALL_ACTION_REQUEST = "GET_ALL_ACTION_REQUEST";
export const GET_ALL_ACTION_SUCCESS = "GET_ALL_ACTION_SUCCESS";
export const GET_ALL_ACTION_FAIL = "GET_ALL_ACTION_FAIL";
export const GET_MY_ACTION_REQUEST = "GET_MY_ACTION_REQUEST";
export const GET_MY_ACTION_SUCCESS = "GET_MY_ACTION_SUCCESS";
export const GET_MY_ACTION_FAIL = "GET_MY_ACTION_FAIL";
export const GET_LOGGED_ACTION_REQUEST = "GET_LOGGED_ACTION_REQUEST";
export const GET_LOGGED_ACTION_SUCCESS = "GET_LOGGED_ACTION_SUCCESS";
export const GET_LOGGED_ACTION_FAIL = "GET_LOGGED_ACTION_FAIL";

export type ActionTypes =
  | typeof RESET_ACTION
  | typeof RESET_ACTION_LOGGING
  | typeof ADD_ACTION_REQUEST
  | typeof ADD_ACTION_SUCCESS
  | typeof ADD_ACTION_FAIL
  | typeof GET_ALL_ACTION_REQUEST
  | typeof GET_ALL_ACTION_SUCCESS
  | typeof GET_ALL_ACTION_FAIL
  | typeof GET_LOGGED_ACTION_REQUEST
  | typeof GET_LOGGED_ACTION_SUCCESS
  | typeof GET_LOGGED_ACTION_FAIL
  | typeof GET_MY_ACTION_REQUEST
  | typeof GET_MY_ACTION_SUCCESS
  | typeof GET_MY_ACTION_FAIL;
